### ISSUE TITLE
Do is work with arcGIS Server 10.3?

### ISSUE THREAD

**Issue by scaddenp** [WSDOT-GIS/LayerMetadataSoe#10]
Also, we create all our data with the iso19139 profile. Can we get it out in the data format?

**Comment by JeffJacobson** [comment]
It should work with ArcGIS Server 10.3 without any problems. (If it doesn't work, be sure to create another issue.)

Regarding iso19139, I think you should at least be able to return the metadata in XML format. It's possible that returning as HTML may fail. We have a [JavaScript library](https://github.com/WSDOT-GIS/geospatialMetadata) that should be able to convert that XML into HTML, though.
